version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nats_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: syuzanna.
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

volumes:
  pg_data: